// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace PizzaAndWings.Migrations
{
    [DbContext(typeof(PizzaAndWingsDbContext))]
    [Migration("20240415212124_UpdateImages")]
    partial class UpdateImages
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PizzaAndWings.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("OrderPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Image = "https://img.freepik.com/free-photo/delicious-salami-pizza_1004-25.jpg?w=1060&t=st=1695335449~exp=1695336049~hmac=d1295d34e9c24f8fe810a224c6d9df4f57187cf53d9821936ee6f19841d93ec4",
                            Name = "Pepperoni Pizza",
                            OrderPrice = 15.99m
                        },
                        new
                        {
                            Id = 2,
                            Image = "https://www.fearlessdining.com/wp-content/uploads/2022/01/gluten-free-pizza-baked.jpg",
                            Name = "Cheese Pizza",
                            OrderPrice = 26.50m
                        },
                        new
                        {
                            Id = 3,
                            Image = "https://img.freepik.com/premium-photo/bowl-buffalo-wings-with-blue-cheese-dip_165536-1438.jpg?w=740",
                            Name = "Hot Wings",
                            OrderPrice = 10.00m
                        },
                        new
                        {
                            Id = 4,
                            Image = "https://img.freepik.com/free-photo/grilled-buffalo-chicken-wings-rustic-wood-plate-generated-by-ai_188544-26049.jpg?t=st=1695269635~exp=1695273235~hmac=3648a5821bd73b68656d30e830d1cf119f11e710dd2f8f16a435f7eee2ea1f3d&w=740",
                            Name = "Meaty Pizza",
                            OrderPrice = 12.00m
                        },
                        new
                        {
                            Id = 5,
                            Image = "https://cdn.pixabay.com/photo/2014/07/08/12/34/pizza-386717_1280.jpg",
                            Name = "Supreme Pizza",
                            OrderPrice = 12.00m
                        },
                        new
                        {
                            Id = 6,
                            Image = "https://img.freepik.com/premium-photo/delicious-juicy-grilled-chicken-meat-bites-with-salt-spices-herbs-dark-concrete-background_73989-48890.jpg?w=740",
                            Name = "BBQ Wings",
                            OrderPrice = 13.00m
                        },
                        new
                        {
                            Id = 7,
                            Image = "https://img.freepik.com/premium-photo/delicious-juicy-grilled-chicken-meat-bites-with-salt-spices-herbs-dark-concrete-background_73989-48890.jpg?w=740",
                            Name = "Boneless Wings",
                            OrderPrice = 14.00m
                        },
                        new
                        {
                            Id = 8,
                            Image = "https://img.freepik.com/free-photo/baked-chicken-wings-asian-style_2829-10160.jpg?w=740&t=st=1695269789~exp=1695270389~hmac=45183c312a4fc8069a1c31d0bd28eb43dc76b80028f737610a49fa1c4f859b97",
                            Name = "Buffalo Wings",
                            OrderPrice = 12.00m
                        },
                        new
                        {
                            Id = 9,
                            Image = "https://images.unsplash.com/photo-1594007654729-407eedc4be65?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1328&q=80",
                            Name = "Cheese Stuffed Crust Pizza",
                            OrderPrice = 22.00m
                        });
                });

            modelBuilder.Entity("PizzaAndWings.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateClosed")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrderTypeId")
                        .HasColumnType("integer");

                    b.Property<int?>("PaymentTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("Tip")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("OrderTypeId");

                    b.HasIndex("PaymentTypeId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateClosed = new DateTime(2024, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "shari@shari.com",
                            FirstName = "Shari",
                            LastName = "Berry",
                            OrderTypeId = 2,
                            PaymentTypeId = 1,
                            Phone = "615-999-7777",
                            Status = false,
                            Tip = 6.00m
                        },
                        new
                        {
                            Id = 2,
                            DateClosed = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Joey@yahoo.com",
                            FirstName = "Joey",
                            LastName = "Boe",
                            OrderTypeId = 1,
                            PaymentTypeId = 2,
                            Phone = "615-322-7337",
                            Status = false,
                            Tip = 9.00m
                        },
                        new
                        {
                            Id = 3,
                            DateClosed = new DateTime(2024, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tim@gmail.com",
                            FirstName = "Tim",
                            LastName = "Ebert",
                            OrderTypeId = 1,
                            PaymentTypeId = 3,
                            Phone = "615-229-2227",
                            Status = false,
                            Tip = 6.00m
                        },
                        new
                        {
                            Id = 4,
                            DateClosed = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Sam@gmail.com",
                            FirstName = "Sam",
                            LastName = "Hill",
                            OrderTypeId = 2,
                            PaymentTypeId = 1,
                            Phone = "615-555-9997",
                            Status = false,
                            Tip = 7.00m
                        });
                });

            modelBuilder.Entity("PizzaAndWings.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("PizzaAndWings.Models.OrderType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OrderTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Type = "In Person"
                        },
                        new
                        {
                            Id = 2,
                            Type = "Phone"
                        });
                });

            modelBuilder.Entity("PizzaAndWings.Models.PaymentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PaymentTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Type = "Card"
                        },
                        new
                        {
                            Id = 2,
                            Type = "Cash"
                        },
                        new
                        {
                            Id = 3,
                            Type = "Check"
                        });
                });

            modelBuilder.Entity("PizzaAndWings.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Uid")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1
                        });
                });

            modelBuilder.Entity("PizzaAndWings.Models.Order", b =>
                {
                    b.HasOne("PizzaAndWings.Models.OrderType", "OrderType")
                        .WithMany()
                        .HasForeignKey("OrderTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PizzaAndWings.Models.PaymentType", "PaymentType")
                        .WithMany()
                        .HasForeignKey("PaymentTypeId");

                    b.Navigation("OrderType");

                    b.Navigation("PaymentType");
                });

            modelBuilder.Entity("PizzaAndWings.Models.OrderItem", b =>
                {
                    b.HasOne("PizzaAndWings.Models.Item", "Item")
                        .WithMany("Order")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PizzaAndWings.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("PizzaAndWings.Models.Item", b =>
                {
                    b.Navigation("Order");
                });

            modelBuilder.Entity("PizzaAndWings.Models.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
